name: Docker Image CI

on:
  push:
    branches: [ "custom" ]
  workflow_dispatch:

env:
  GHCR_IMAGE: ghcr.io/${{ github.repository_owner }}/openlist_api_server

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Log in to the Container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push latest image to GHCR
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile
        push: true
        tags: ${{ env.GHCR_IMAGE }}:latest
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.description=OpenList API Server

    - name: Build and push alpine image to GHCR
      uses: docker/build-push-action@v3
      with:
        context: .
        file: ./Dockerfile-Lite
        push: true
        tags: ${{ env.GHCR_IMAGE }}:alpine
        labels: |
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.description=OpenList API Server
